name: Publish to GitHub Pages
on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - 'playbook-antora.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'docs-template' && !startsWith(github.event.head_commit.message, 'Initial commit')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Repository Description
        run: |
          DESCRIPTION=$(head -1 README.adoc)
          gh repo edit --description "${DESCRIPTION/= /}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Antora and the Antora Lunr Extension
        run: npm i antora @antora/lunr-extension
      - name: Install Asciidoctor Extension
        run: npm i asciidoctor-kroki asciidoctor-highlight.js
      - name: Generate Site
        run: npx antora --key updated="$(date '+%Y-%m-%d %H:%M:%S')" playbook-antora.yml
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: build/site